
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import Starfield from "./Components/Starfield";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* /// */}
        <main className="relative w-full min-h-screen overflow-x-hidden bg-slate-950 text-slate-100 selection:bg-indigo-500/30">
          {/* Background Layer */}
          <Starfield />
          <div className="absolute inset-0 z-1 bg-gradient-to-b from-transparent via-slate-950/50 to-slate-950" />

          {/* Dynamic Ambient Glow */}
          <div className="absolute top-1/4 -left-20 w-96 h-96 bg-indigo-600/20 rounded-full blur-[120px] animate-pulse" />
          <div className="absolute bottom-1/4 -right-20 w-96 h-96 bg-purple-600/10 rounded-full blur-[120px] animate-pulse" style={{ animationDelay: '1s' }} />

          <Navbar />
          {children}
          <Footer />

        </main>
       
      </body>
    </html>
  );
}
